version: '3.7'

services:
  web:
    build: .
    labels:
      - "traefik.frontend.rule=Host:lbhello.localhost"
    networks:
      - frontend

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend

networks:
  frontend:
